// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddROMFiles(arg1:string,arg2:Array<string>,arg3:boolean):Promise<Array<string>>;

export function CancelInstall():Promise<void>;

export function CleanBuildDir(arg1:string):Promise<void>;

export function GetActiveInstall():Promise<string>;

export function GetGames():Promise<Array<models.VideoGame>>;

export function GetInstallPrompts(arg1:string):Promise<Array<models.ArgPrompt>>;

export function GetInstallState(arg1:string):Promise<models.InstallState>;

export function GetPlatform():Promise<string>;

export function GetPlatformAvailable(arg1:string):Promise<boolean>;

export function GetROMStatus(arg1:string):Promise<Record<string, boolean>>;

export function GetRomLibraryStatus():Promise<Record<string, boolean>>;

export function GetRoms():Promise<Array<models.VideoGameRom>>;

export function GetSettings():Promise<main.Settings>;

export function GetVersions():Promise<Array<models.VideoGameVersion>>;

export function ImportROMs(arg1:Array<models.ROMFileMatch>,arg2:boolean):Promise<void>;

export function InstallVersion(arg1:string,arg2:Record<string, string>):Promise<void>;

export function LaunchVersion(arg1:string,arg2:string):Promise<void>;

export function MatchDroppedROMs(arg1:Array<string>):Promise<models.ROMDropSummary>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function UninstallVersion(arg1:string):Promise<void>;

export function ValidateMediaItemsPath():Promise<string>;
