// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddROMFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddROMFiles'](arg1, arg2, arg3);
}

export function CancelDump() {
  return window['go']['main']['App']['CancelDump']();
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CheckMediaItemsUpdate() {
  return window['go']['main']['App']['CheckMediaItemsUpdate']();
}

export function CleanBuildDir(arg1) {
  return window['go']['main']['App']['CleanBuildDir'](arg1);
}

export function GetActiveInstall() {
  return window['go']['main']['App']['GetActiveInstall']();
}

export function GetDefaultPaths() {
  return window['go']['main']['App']['GetDefaultPaths']();
}

export function GetDuckStationPath() {
  return window['go']['main']['App']['GetDuckStationPath']();
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetInstallPrompts(arg1) {
  return window['go']['main']['App']['GetInstallPrompts'](arg1);
}

export function GetInstallState(arg1) {
  return window['go']['main']['App']['GetInstallState'](arg1);
}

export function GetItemUpdate(arg1) {
  return window['go']['main']['App']['GetItemUpdate'](arg1);
}

export function GetMediaItemsSHA() {
  return window['go']['main']['App']['GetMediaItemsSHA']();
}

export function GetOpticalDrives() {
  return window['go']['main']['App']['GetOpticalDrives']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPlatformAvailable(arg1) {
  return window['go']['main']['App']['GetPlatformAvailable'](arg1);
}

export function GetROMStatus(arg1) {
  return window['go']['main']['App']['GetROMStatus'](arg1);
}

export function GetRedumperPath() {
  return window['go']['main']['App']['GetRedumperPath']();
}

export function GetRom(arg1) {
  return window['go']['main']['App']['GetRom'](arg1);
}

export function GetRomFilePaths(arg1) {
  return window['go']['main']['App']['GetRomFilePaths'](arg1);
}

export function GetRomLibraryStatus() {
  return window['go']['main']['App']['GetRomLibraryStatus']();
}

export function GetRomState(arg1) {
  return window['go']['main']['App']['GetRomState'](arg1);
}

export function GetRoms() {
  return window['go']['main']['App']['GetRoms']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion(arg1) {
  return window['go']['main']['App']['GetVersion'](arg1);
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function ImportROMs(arg1, arg2) {
  return window['go']['main']['App']['ImportROMs'](arg1, arg2);
}

export function InstallVersion(arg1, arg2) {
  return window['go']['main']['App']['InstallVersion'](arg1, arg2);
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function LaunchRom(arg1, arg2) {
  return window['go']['main']['App']['LaunchRom'](arg1, arg2);
}

export function LaunchVersion(arg1, arg2) {
  return window['go']['main']['App']['LaunchVersion'](arg1, arg2);
}

export function MatchDroppedROMs(arg1) {
  return window['go']['main']['App']['MatchDroppedROMs'](arg1);
}

export function RefreshLibraryIndex() {
  return window['go']['main']['App']['RefreshLibraryIndex']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanDiscs() {
  return window['go']['main']['App']['ScanDiscs']();
}

export function SelectExecutable() {
  return window['go']['main']['App']['SelectExecutable']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetDuckStationPath(arg1) {
  return window['go']['main']['App']['SetDuckStationPath'](arg1);
}

export function SetRedumperPath(arg1) {
  return window['go']['main']['App']['SetRedumperPath'](arg1);
}

export function StartDump(arg1, arg2) {
  return window['go']['main']['App']['StartDump'](arg1, arg2);
}

export function SyncMediaItems() {
  return window['go']['main']['App']['SyncMediaItems']();
}

export function UninstallVersion(arg1) {
  return window['go']['main']['App']['UninstallVersion'](arg1);
}

export function UpdateMediaItem(arg1) {
  return window['go']['main']['App']['UpdateMediaItem'](arg1);
}

export function ValidateMediaItemsPath() {
  return window['go']['main']['App']['ValidateMediaItemsPath']();
}
