// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddROMFiles(arg1:string,arg2:Array<string>,arg3:boolean):Promise<Array<string>>;

export function CancelDump():Promise<void>;

export function CancelInstall():Promise<void>;

export function CheckMediaItemsUpdate():Promise<boolean>;

export function CleanBuildDir(arg1:string):Promise<void>;

export function GetActiveInstall():Promise<string>;

export function GetDefaultPaths():Promise<Record<string, string>>;

export function GetDuckStationPath():Promise<string>;

export function GetGames():Promise<Array<models.VideoGame>>;

export function GetInstallPrompts(arg1:string):Promise<Array<models.ArgPrompt>>;

export function GetInstallState(arg1:string):Promise<models.InstallState>;

export function GetItemUpdate(arg1:string):Promise<boolean>;

export function GetMediaItemsSHA():Promise<string>;

export function GetOpticalDrives():Promise<Array<models.OpticalDrive>>;

export function GetPlatform():Promise<string>;

export function GetPlatformAvailable(arg1:string):Promise<boolean>;

export function GetROMStatus(arg1:string):Promise<Record<string, boolean>>;

export function GetRedumperPath():Promise<string>;

export function GetRom(arg1:string):Promise<models.VideoGameRom>;

export function GetRomFilePaths(arg1:string):Promise<Record<string, string>>;

export function GetRomLibraryStatus():Promise<Record<string, boolean>>;

export function GetRomState(arg1:string):Promise<models.RomState>;

export function GetRoms():Promise<Array<models.VideoGameRom>>;

export function GetSettings():Promise<main.Settings>;

export function GetVersion(arg1:string):Promise<models.VideoGameVersion>;

export function GetVersions():Promise<Array<models.VideoGameVersion>>;

export function ImportROMs(arg1:Array<models.ROMFileMatch>,arg2:boolean):Promise<void>;

export function InstallVersion(arg1:string,arg2:Record<string, string>):Promise<void>;

export function IsDevMode():Promise<boolean>;

export function LaunchRom(arg1:string,arg2:string):Promise<void>;

export function LaunchVersion(arg1:string,arg2:string):Promise<void>;

export function MatchDroppedROMs(arg1:Array<string>):Promise<models.ROMDropSummary>;

export function RefreshLibraryIndex():Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function ScanDiscs():Promise<Array<models.OpticalDrive>>;

export function SelectExecutable():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetDuckStationPath(arg1:string):Promise<void>;

export function SetRedumperPath(arg1:string):Promise<void>;

export function StartDump(arg1:string,arg2:string):Promise<void>;

export function SyncMediaItems():Promise<void>;

export function UninstallVersion(arg1:string):Promise<void>;

export function UpdateMediaItem(arg1:string):Promise<void>;

export function ValidateMediaItemsPath():Promise<string>;
