// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddROMFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddROMFiles'](arg1, arg2, arg3);
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CleanBuildDir(arg1) {
  return window['go']['main']['App']['CleanBuildDir'](arg1);
}

export function GetActiveInstall() {
  return window['go']['main']['App']['GetActiveInstall']();
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetInstallPrompts(arg1) {
  return window['go']['main']['App']['GetInstallPrompts'](arg1);
}

export function GetInstallState(arg1) {
  return window['go']['main']['App']['GetInstallState'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPlatformAvailable(arg1) {
  return window['go']['main']['App']['GetPlatformAvailable'](arg1);
}

export function GetROMStatus(arg1) {
  return window['go']['main']['App']['GetROMStatus'](arg1);
}

export function GetRomLibraryStatus() {
  return window['go']['main']['App']['GetRomLibraryStatus']();
}

export function GetRoms() {
  return window['go']['main']['App']['GetRoms']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function ImportROMs(arg1, arg2) {
  return window['go']['main']['App']['ImportROMs'](arg1, arg2);
}

export function InstallVersion(arg1, arg2) {
  return window['go']['main']['App']['InstallVersion'](arg1, arg2);
}

export function LaunchVersion(arg1, arg2) {
  return window['go']['main']['App']['LaunchVersion'](arg1, arg2);
}

export function MatchDroppedROMs(arg1) {
  return window['go']['main']['App']['MatchDroppedROMs'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function UninstallVersion(arg1) {
  return window['go']['main']['App']['UninstallVersion'](arg1);
}

export function ValidateMediaItemsPath() {
  return window['go']['main']['App']['ValidateMediaItemsPath']();
}
